name: test

on: pull_request

permissions:
  pull-requests: write
  contents: write


jobs:
  test:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker Build
        run: docker-compose build
      - name: Docker Compose Up
        run: docker-compose up -d
      - name: pytest
        run: docker-compose run -T --entrypoint "poetry run pytest" demo-app
      - name: linter
        run: docker-compose run -T --entrypoint "poetry run task lint" demo-app
      - name: formater
        run: docker-compose run --entrypoint "poetry run task fmt" demo-app


  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  